server:
  port: 18092
spring:
  application:
    name: pay
  main:
    allow-bean-definition-overriding: true
  rabbitmq:
    host: 192.168.72.129
    username: guest
    password: guest
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:7001/eureka
  instance:
    prefer-ip-address: true
feign:
  hystrix:
    enabled: true

#hystrix 配置
hystrix:
  command:
    default:
      execution:
        timeout:
          #如果enabled设置为false，则请求超时交给ribbon控制
          enabled: true
        isolation:
          strategy: SEMAPHORE

#微信支付信息配置
weixin:
  # 应用id
  appid: wx8397f8696b538317
  # 商户id
  partner: 1473426802
  # 秘钥
  partnerkey: T6m9iK73b0kn9g5v426MKfHQH7X8rKwb
  #回调地址
  notifyurl: http://www.itcast.cn/weixin/pay/notify/url

#位置支付交换机和队列
#mq:
#  pay:
#    exchange:
#      order: exchange.order
#    queue:
#      order: queue.order
#    routing:
#      key: queue.order

# 位置支付交换机和队列
mq:
  pay:
    exchange:
      order: exchange.order
    queue:
      order: queue.order
      seckillorder: queue.seckillorder
      seckillordertimer: queue.seckillordertimer
      seckillordertimerdelay: queue.seckillordertimerdelay
    routing:
      orderkey: queue.order
      seckillorderkey: queue.seckillorder