server:
  port: 18081
spring:
  application:
    name: goods
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.72.129:3306/changgou_goods?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: 123456
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://47.100.59.134:3306/mall?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
#    username: root
#    password: lz29885328

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:7001/eureka
  instance:
    prefer-ip-address: true
feign:
  hystrix:
    enabled: true

# 使用通用mapper可以不用mybatis
#mybatis:
#  configuration:
#    map-underscore-to-camel-case: true
#  mapper-locations: classpath:mapper/*Mapper.xml
#  type-aliases-package: com.changgou.goods.pojo